Fix/babo/nav bar cleanup
socious-io/socious-web-app pull request #145
Opened 2022-10-12 05:11 UTC by nibab-boo

> Let me request for Project Image first

- [ ] Fixed image on Banner
- [ ] Nested selection for Nav-link
- [ ] Fixed Icon fill for Top & Bottom. But, there is a small issue for Project. Icon looks smaller. I would be helpful if you could share a way to fix it.
- [ ] removed unnecessary import and fixed margin for bottom nav

2022-10-12 12:36 UTC, lalomartins requested changes
looks good otherwise 🙏

2022-10-12 12:36 UTC, lalomartins commented on layout/GeneralLayout/index.tsx
> +    img: projectImg,
network

2022-10-13 02:00 UTC, nibab-boo commented on layout/GeneralLayout/index.tsx
> +    img: projectImg,
We still don't have the network img.

2022-10-13 06:25 UTC, lalomartins commented on layout/GeneralLayout/index.tsx
> +    img: projectImg,
ah yes, yesterday I thought this was the icon. I guess it's good enough for now then

2022-10-13 06:25 UTC, lalomartins approved these changes

2022-10-13 06:25 UTC, merged