#141_Project_User : implement get user projects
socious-io/socious-web-app pull request #175
Opened 2022-10-18 15:32 UTC by misa-qarahqani

implement get user projects

2022-10-19 06:58 UTC, lalomartins requested changes
Hi @misa-qarahqani 

The code looks really good, but we're using SWR for all such get requests. Can you show me a version using SWR? Thanks.

2022-10-19 07:48 UTC, misa-qarahqani commented
Sure. Just give me time for tonight. Thx 🙂

On Wed, 19 Oct 2022, 08:58 Lalo Martins, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @misa-qarahqani <https://github.com/misa-qarahqani>
>
> The code looks really good, but we're using SWR for all such get requests.
> Can you show me a version using SWR? Thanks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/socious-io/socious-web-app/pull/175#pullrequestreview-1146950175>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3UHIVVS3GJ5DGN2D5JGG6LWD6LYXANCNFSM6AAAAAARIG5DQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-19 13:57 UTC, lalomartins approved these changes

2022-10-19 14:10 UTC, lalomartins requested changes
Hmm okay. Now that I can test it, I'm afraid it's not quite right.

- Please expand the first box that isn't empty
- The card title should be the project name, not the cover letter
- The organization avatar and should be displayed
- Please make ‘Pending’ capital P
- The main column is too narrow, it should be the same width as most pages such as /projects

![image](https://user-images.githubusercontent.com/1211455/196715240-86b46293-a85a-492e-8c19-c0f4f44101db.png)

2022-10-19 14:15 UTC, misa-qarahqani commented
now the photo is more high quality. and can see better :D.
what about the project title? it should be in the response as which
property?
Thanks

On Wed, Oct 19, 2022 at 4:10 PM Lalo Martins ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hmm okay. Now that I can test it, I'm afraid it's not quite right.
>
>    - Please expand the first box that isn't empty
>    - The card title should be the project name, not the cover letter
>    - The organization avatar and should be displayed
>    - Please make ‘Pending’ capital P
>    - The main column is too narrow, it should be the same width as most
>    pages such as /projects
>
> [image: image]
> <https://user-images.githubusercontent.com/1211455/196715240-86b46293-a85a-492e-8c19-c0f4f44101db.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/socious-io/socious-web-app/pull/175#pullrequestreview-1147656689>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3UHIVVS6LNLQCSB7C5O3VTWD76OHANCNFSM6AAAAAARIG5DQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-19 14:25 UTC, lalomartins commented
> now the photo is more high quality. and can see better :D. what about the project title? it should be in the response as which property? Thanks

I'm afraid that data won't be in the response, you'll have to make another request per project using the project id. But the project response in turn will have the organization details in the `identity_meta` property.

2022-10-20 09:38 UTC, misa-qarahqani commented
I applied changes based on the points that u mentioned.

On Wed, Oct 19, 2022 at 4:25 PM Lalo Martins ***@***.***>
wrote:

> now the photo is more high quality. and can see better :D. what about the
> project title? it should be in the response as which property? Thanks
>
> I'm afraid that data won't be in the response, you'll have to make another
> request per project using the project id. But the project response in turn
> will have the organization details in the identity_meta property.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/socious-io/socious-web-app/pull/175#issuecomment-1284104043>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3UHIVX25WXNF3VGTYLLJQTWEAAFLANCNFSM6AAAAAARIG5DQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-20 09:58 UTC, lalomartins commented
> I applied changes based on the points that u mentioned.
Thanks, I'll take another look.

2022-10-20 10:14 UTC, lalomartins approved these changes

2022-10-20 10:16 UTC, lalomartins requested changes
looks good, just one small fix left

2022-10-20 10:17 UTC, lalomartins commented on components/common/Project/MyApplication/index.tsx
> +let groupByStatus: any;
then if you define it that way, there's no need for type, as it will be inferred correctly by the compiler 😸

2022-10-20 12:03 UTC, misa-qarahqani commented
it cant use as const, because as u see we use it into the function and
value is changeable. and it's not state , so it's better that not to be
inside the function. like material ui and ant , ... uses. how ever it could
be inside too.

On Thu, Oct 20, 2022 at 12:17 PM Lalo Martins ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In components/common/Project/MyApplication/index.tsx
> <https://github.com/socious-io/socious-web-app/pull/175#discussion_r1000438472>
> :
>
> > -  },
>
> -  {
>
> -    id: 2,
>
> -    projectId: '2',
>
> -  },
>
> -  {
>
> -    id: 3,
>
> -    projectId: '3',
>
> -  },
>
> -];
>
> +import {useToggle} from ***@***.***';
>
> +import {IUserProjects} from ***@***.***/project';
>
> +import {get} from 'utils/request';
>
> +
>
> +// todo : type for groupByStatus
>
> +let groupByStatus: any;
>
>
> then if you define it that way, there's no need for type, as it will be
> inferred correctly by the compiler 😸
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/socious-io/socious-web-app/pull/175#discussion_r1000438472>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3UHIVXQR6GNKUNAKFCQXSTWEEL3PANCNFSM6AAAAAARIG5DQA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-20 12:12 UTC, misa-qarahqani commented on components/common/Project/MyApplication/index.tsx
> +let groupByStatus: any;
t cant use as const, because as u see we use it into the function and
value is changeable. and it's not state , so it's better that not to be
inside the function. like material ui and ant , ... uses. how ever it could
be inside too.
so plz let me know for changes or not.
thx

2022-10-20 13:38 UTC, merged