responsive menu bar
socious-io/socious-web-app pull request #42
Opened 2022-09-14 11:54 UTC by sooodi

I added some images &  I forgot to cover the file navbar. I did them now

2022-09-14 12:10 UTC, lalomartins commented
wth… where is the Cloudflare comment? 🤯 It build successfully to https://sudy-604-main-layout-and-men.socious-web-app.pages.dev/

2022-09-14 12:19 UTC, lalomartins requested changes
Under a certain width, an unneeded padding appears on the right side

https://user-images.githubusercontent.com/1211455/190151644-ff8c64e3-9660-423c-854a-a38370257b42.mp4

2022-09-14 12:19 UTC, lalomartins commented on .gitignore
> +package-lock.json
```suggestion
package-lock.json
```

2022-09-14 12:19 UTC, lalomartins commented on frontend-next/.prettierrc
> -}
You're deleting this but you didn't move the options to `prettier.config.js`, so the formatting for the whole repository changed

2022-09-14 12:19 UTC, lalomartins commented on .gitignore
> +package-lock.json
also should add .DS_Store, not sure why it wasn't here already

2022-09-14 14:31 UTC, sooodi commented on .gitignore
> +package-lock.json
ok

2022-09-15 05:07 UTC, sooodi commented on .gitignore
> +package-lock.json
@lalomartins  please see my branch   .DS_Store existed

2022-09-15 05:22 UTC, lalomartins commented on .gitignore
> +package-lock.json
I mean it should be added to .gitignore. But that's ok, it doesn't need to be in this PR, I'll sort it out later

2022-09-15 05:51 UTC, sooodi commented on frontend-next/.prettierrc
> -}
@lalomartins  done

2022-09-15 05:56 UTC, sooodi commented
> wth… where is the Cloudflare comment? 🤯 It build successfully to https://sudy-604-main-layout-and-men.socious-web-app.pages.dev/

@lalomartins  that happend becuase  of merge .it is ok now

2022-09-15 08:08 UTC, closed without merging