Web3 integration Pt.1
socious-io/socious-web-app pull request #5
Opened 2022-07-15 09:12 UTC by gpablo6

Includes:
- Restructure of project directory
- Change of Web3 React-Interface
- Implementation of Contract Functionalities
- Implementation of components for Donate contract

Pending:
- Minor fixed to Escrow functions
- Implementation of components for Escrow contract

2022-07-15 11:36 UTC, rodrigopavezi commented on scripts/donations.ts
> +    const contractAddress = "0xE1bF07E88D873E943755595E5401DCB222eF4725"
I think this contract address should go the the .env so you can switch between test and main nets. 

More info on how to do it here: https://nextjs.org/docs/basic-features/environment-variables

2022-08-08 17:28 UTC, lalomartins commented
Can you please undo the repo restructuring. It's a good idea, but it should never be done inside such a big branch, as it makes the PR more or less impossible to review and very difficult to merge. We can restructure the repo separately after this is merged.

2022-08-08 17:28 UTC, lalomartins requested changes
Can you please undo the repo restructuring. It's a good idea, but it should never be done inside such a big branch, as it makes the PR more or less impossible to review and very difficult to merge. We can restructure the repo separately after this is merged.

2022-09-06 05:59 UTC, lalomartins commented
The backend branch is now merged to main, so when this branch is building, we can merge it too. Let me know 😸

2022-10-06 11:36 UTC, closed without merging